Hw05 avatars
kvitkovsky1302/nodejs-homework-rest-api pull request #6
Opened 2021-11-27 16:18 UTC by kvitkovsky1302

2021-11-27 18:44 UTC, KirillKulakow commented on controllers/authControllers.js
> +  const avatarURL = gravatar.url(email);
добавить опцию протокола

2021-11-27 18:47 UTC, KirillKulakow commented on middlewares/upload.js
> +  filename: (req, file, cb) => {
можно добавить фильтрацию по MIME типу файла

2021-11-27 18:48 UTC, KirillKulakow requested changes
Need some fix

2021-11-27 20:29 UTC, kvitkovsky1302 commented on controllers/authControllers.js
> +  const avatarURL = gravatar.url(email);
Добавил

2021-11-27 20:29 UTC, kvitkovsky1302 commented on middlewares/upload.js
> +  filename: (req, file, cb) => {
Добавил

2021-11-28 21:52 UTC, KirillKulakow approved these changes

2021-11-30 11:10 UTC, merged